/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Persona(private var nombre: String, private var apellido: String, private var edad: Int
) {
    override fun toString(): String {
        return "Persona: Nombre=${nombre}, Apellido=${apellido}, Edad=${edad}"
    }
}

fun main() {
    var persona: Persona 
    persona = Persona("Bauti", "Mini", 16) 
    println(persona)
}